---
name: Mingyu
surname: Wang
position: "PhD Candidate"
address: "Department of Sociology, Tsinghua  University"
phone: +86 13051776630
www: wmymingyu.github.io
email: "wmy18@mails.tsinghua.edu.cn"
github: wmymingyu
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
headcolor: "414141"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD in Sociology", "2018-Now", "Tsinghua University", "Beijing, China",
  "Bachelor of Laws", "2014-2018", "Shandong University", "Jinan, China",
  "Exchange Student", "Feb.-June. 2017", "National Chengchi University", "Taiwan, China"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Working Paper

```{R}

WP <- tibble::tribble(
  ~ name, ~ date, ~ organization, ~ location,
  "Health's Social Resilience: A Structural Framework", "2021", "Chenggang Zhang, & Mingyu Wang", "Contributing to ‘International Journal of Environmental Research and Public Health’, Switzerland",
  "A Study on the Types of Environmental Risks and Governance Strategies in Countries Along the ‘Belt and Road’", "2021", "Chenggang Zhang, & Mingyu Wang", "forthcoming in ‘China Soft Science Magazine’, China",
  "The Historical Evolution and Contemporary Construction of Sociology of Technology", "2021", "Chenggang Zhang, & Mingyu Wang", "forthcoming in ‘Academic Forumh’, China",
  )
WP %>%
  detailed_entries(what = location, when = organization, with = name, where = date)

```

# Research Experience

## Social Governance

```{r}
SG <- tibble::tribble(
  ~ actor, ~ date, ~ name, ~ location, ~ details,
  "Research Leader", "Jan. 2021", "Study on Poverty Alleviation and Rural Revitalization Strategy", "Beijing, China", c("Investigated the current situation of rural governance in Wushan County, Chongqing City, China.", "Wrote a research report entitled One-Core and Multiple-Governance"),
  "Research Associate", "Nov. 2020", "Research on the Construction of Emergency Management System for Public Emergencies", "Beijing, China", "Investigated the current situation of emergency management of public emergencies in Taizhou city, Jiangsu Province, China",
  "Research Associate", "Fer. 2020", "The Bibliography of ‘Social Governance in the Information Age’", "Beijing, China", "In charge of the chapter ‘The Influence of Internet on Social Governance’",
  "Research Associate", "Dec. 2019", "Study on Zhoushan City's Digital Governance Ability", "Beijing, China", "Wrote investigation report about ‘Zhoushan City's Digital Governance Ability and Development’ (The report was selected as a case of China's digital governance innovation)",
  "Research Associate", "Dec. 2018", "Study on Social Governance Ability and System Modernization Strategy of Qinghai Province", "Beijing, China", c("Wrote literature review of ‘Governance’ and ‘Social Governance’", "Summarized the Problems of Social Governance and Development in Qinghai Province"),
  "Research Associate", "Dec. 2018", "Study of China Social Governance and Development Index", "Beijing, China", c("Collected information on the development of social governance in China", "Constructed ‘China Social Governance and Development Index’"),
  "Principal Investigator", "June. 2018", "Study on Rural Governance in Jinan", "Jinan, China", c("Designed the research framework", "Wrote the project report about ‘Jinan in-depth Implementation of Rural Revitalization Strategy Research’"),
  "Principal Investigator", "Feb. 2018", " Study on the Normalization of Beautiful City Governance in Jinan", "Jinan, China", c("Designed the research framework and division of labor", "Wrote the project report ‘The Normalization of Jinan's Construction of Beautiful City’")
  )
SG %>%
  detailed_entries(what = actor, when = location, with = name, where = date, why = details)
```

## Risk Governance

```{r}
RG <- tibble::tribble(
  ~ actor, ~ date, ~ name, ~ location, ~ details,
  "Research Member", "2019 - now", "Research on the Main Risks and Countermeasures Faced by the Construction of the BRI", "Beijing, China", c(
    "Project of Philosophy and Social Science Foundation of China[18VDL015]",
    "Paying attention to environmental risk content: “Formulate Governance Strategies Based on Economic Corridors: Types of Environmental Risks and Governance Strategies in Countries Along the ‘Belt and Road’” (The paper won the first prize of excellent paper of China Development Strategy Research Association in 2020)",
    "Writing health risk papers: ‘Social Resilience of Health: A Structural Framework’"
  ),
  "Team instructor", "Jan. 2020", "Study on localization of Chinese Companies in Tanzania", "Dar es Salaam, Tanzania", c(
    "Academic instructor of the project team",
    "Designed interview outline and carry out fieldwork in Tanzania",
    "Wrote the project report about ‘Risks of Chinese Enterprises in the Localization Process in Tanzania’"
  ),
  )
RG %>%
  detailed_entries(what = actor, when = location, with = name, where = date, why = details)
```

## Sociology of Technology

```{r}
ST <- tibble::tribble(
  ~ actor, ~ date, ~ name, ~ location, ~ details,
  "Research Member", "Jan. 2020 - now", "Compile Textbook of Sociology of Technology", "Beijing, China", c(
    "Participated in the compilation of the textbook ‘Sociology of Technology: History, Theory and Methods’",
    "Pay attention to the basic concepts of sociology of technology and discuss technology in sociology",
    "This will be China’s first systematic textbook of sociology of technology"
  ),
  "Team Leader", "Oct. 2020 - now", "Research on Classic Works of Sociology of Technology", "Beijing, China", c(
    "Selected international classics of sociology of technology, and translated to Chinese",
    "Compiled ‘Classical Readings in the Sociology of Technology: Historical Evolution and Contemporary Construction’",
    "Combed the development of sociology of technology and China's path"
  )
)
ST %>%
  detailed_entries(what = actor, when = location, with = name, where = date, why = details)
```

# AWARDS

```{r}
awards <- tibble::tribble(
  ~ name, ~ date, ~ organization, ~ location,
  "Dean Scholarship", "2020", "Tsinghua University", "Beijing, China",
  "Excellent League Member", "2020", "Tsinghua University", "Beijing, China",
  "First Prize of Women's Volleyball Match", "2019", "Tsinghua University", "Beijing, China",
  "Outstanding Graduates in Shandong Province", "2018", "Shandong University", "Jinan, China",
  "First-class Scholarship", "2014-2017", "Shandong University", "Jinan, China",
  "First Finisher of a Patent(Patent of a type of mask for pets [CN206547590U])", "2017", "Shandong University", "Jinan, China",
  "National Scholarship", "2016", "Shandong University", "Jinan, China",
  "Model Student of Academic Records in Shandong Province", "2016", "Shandong University", "Jinan, China",
  "Excellent Student Cadre", "2016", "Shandong University", "Jinan, China",
  "2nd Price of University Students Volleyball League in Shandong", "2016", "Shandong University", "Jinan, China",
  )
awards %>%
  detailed_entries(what = organization, when = location, with = name, where = date)
```

# Skill

```{r}
skill <- tibble::tribble(
  ~ work,
  "Program: Statistical software including R, SPSS",
  "Application: Photography, PS",
  "Language: Korean (Conversational), English (IELTS), Chinese (Native)",
  )
skill %>%
  detailed_entries(why = work)
```

